name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with: 
        flutter-version: '2.1.x'
    - run: flutter pub get
    - run: flutter build apk
    - name: Get Apk Version
      uses: JantHsueh/get-apk-info-action@1.0
      with: 
        apkPath: app/build/outputs/apk/release/app-release.apk

    
    
