name: CI

on: push

jobs:
 build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
    
      with:
        args: pub get

    - name : build apk 

   
    
